version: "3.9"

services:
  backend:
    image: ghcr.io/OWNER/REPO-backend:latest
    restart: unless-stopped
    ports:
      - "3001:3001"

  realtime:
    image: ghcr.io/OWNER/REPO-realtime:latest
    restart: unless-stopped
    ports:
      - "3002:3002"

  frontend:
    image: ghcr.io/OWNER/REPO-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
      - realtime
